### ISSUE TITLE
Post on forums?

### ISSUE THREAD

**Issue by legoboy0215** [PMPlugins/PMPlugins.github.io#2]
Put this link on the forums in off topic: http://pmplugins.github.io/docs/html/annotated.html
They will all want it :P

**Comment by jojoe77777** [comment]
I moved some files around a bit, so it would now be http://pmplugins.github.io/docs/index. But I also added a link to it from the main http://pmplugins.github.io/

**Comment by jojoe77777** [comment]
And the Off-Topic section's description is "Other discussions not related to PocketMine or Minecraft: PE multiplayer (or alike). Advertising is not allowed", but PocketMine docs are related to PocketMine... For now I'll just make a profile post.

**Comment by jojoe77777** [comment]
Well... Now the jenkins site is back up...

**Comment by legoboy0215** [comment]
I know :)
